# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.2'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Allure
        run: |
          curl -o allure-2.24.1.tgz -OLs https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.24.1/allure-commandline-2.24.1.tgz
          sudo tar -zxvf allure-2.24.1.tgz -C /opt/
          sudo ln -s /opt/allure-2.24.1/bin/allure /usr/bin/allure

      - name: Run tests with Allure
        run: |
          xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' make test

      - name: Generate Allure Report
        run: |
          allure generate reports/allure-results --clean -o reports/allure-report

      - name: Verify Allure Report Exists
        run: |
          if [ ! -d "reports/allure-report" ]; then
            echo "Allure report directory is missing!";
            exit 1;
          fi

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: reports/allure-report